import { getVoiceProfile } from '@/data/audio-manifest'
import type { Species } from '@/data/species'

/**
 * The voice signature: each species' artwork, drawn from its own synthesis
 * parameters.
 *
 * WHY NOT AN ILLUSTRATION. The catalog needs artwork (website.md §5) and the
 * obvious answer is one commissioned drawing per species. That answer has two
 * problems: per-species illustration is exactly the linear content cost
 * overview.md §8 names as the binding constraint on catalog growth, and stock
 * bird imagery brings licensing obligations to track per file — for a site
 * whose whole attribution story is "rendered from metadata, never
 * hand-maintained".
 *
 * So the mark for a species is a picture of its voice. Glide contour, vibrato
 * rate and depth, harmonic stack and noise floor are read from the audio
 * manifest — the same numbers engine/voices.py used to synthesize the clip
 * playing beside it. Two species cannot collide, because two identical marks
 * would mean two identical-sounding birds. It is deterministic, about a
 * kilobyte, needs no image request, and carries no third-party rights.
 *
 * This module emits an SVG STRING rather than JSX so that the page artwork and
 * the Open Graph card are generated by one function. An OG image that does not
 * match the page it previews is a bug that only ever shows up in someone
 * else's chat window.
 */

export interface ArtworkOptions {
  width?: number
  height?: number
  /**
   * How many notes to draw across the width.
   *
   * A bird sings a phrase, not one held note, and an encoded message is a run
   * of them — so a wide canvas gets several notes rather than one stretched
   * flat. The note itself is identical in every case; only how many fit
   * changes, which is what keeps a card, a page header and a social card
   * recognisably the same mark.
   */
  notes?: number
}

export function voiceSignatureSvg(
  species: Species,
  { width = 400, height = 200, notes = 1 }: ArtworkOptions = {},
): string {
  const profile = getVoiceProfile(species.slug)
  const { base, accent, wash } = species.palette
  const mid = height / 2

  // Degrade rather than throw if a species ever lacks a profile: a missing
  // mark should cost one card its texture, not take the catalog down.
  const glideHz = profile?.glideHz ?? 0
  const glideShape = profile?.glideShape ?? 'arch'
  const vibratoHz = profile?.vibratoHz ?? 0
  const vibratoDepth = profile?.vibratoDepth ?? 0
  const harmonics = profile?.harmonics ?? [[1, 1]]
  const noise = profile?.noise ?? 0

  // Hz figures scale to pixels so the RATIOS between species — the only part
  // that carries meaning — stay comparable. The offset gives a shallow glide
  // enough amplitude to be visible at thumbnail size; it applies only when
  // there IS a glide, so a genuinely flat voice like the hoopoe still draws as
  // a straight line rather than being given movement it does not have.
  const glideAmp = glideHz > 0 ? Math.min(16 + glideHz * 0.5, height * 0.4) : 0
  const vibAmp = Math.min(vibratoDepth * 1.15, height * 0.16)

  // SAMPLE COUNT IS A PAGE-WEIGHT DECISION, NOT A FIDELITY ONE.
  //
  // These marks are inlined into the HTML, and a server-rendered inline SVG is
  // paid for twice: once in the markup and again, escaped, in the RSC payload.
  // At 200 samples a single species cost ~14 KB, so a six-species preview grid
  // put 166 KB of path data on the critical path of a page with a 2.5s LCP
  // budget. One sample every ~7px is visually indistinguishable here — the
  // curves are smooth and low-frequency — and costs a fraction of that.
  const STROKE_SAMPLES = Math.max(24, Math.min(64, Math.round(width / 7)))
  // Fills tolerate a coarser outline than strokes do.
  const FILL_SAMPLES = Math.max(16, Math.round(STROKE_SAMPLES / 2))

  // Position within the CURRENT note, given a position across the whole width.
  // Notes are separated by a gap, during which nothing is drawn.
  const GAP = 0.12
  const noteAt = (x: number): number | null => {
    const span = 1 / notes
    const local = (x % span) / span
    if (local > 1 - GAP) return null
    return local / (1 - GAP)
  }

  const contourY = (u: number): number => {
    let f: number
    if (glideShape === 'up') f = -glideAmp / 2 + glideAmp * u
    else if (glideShape === 'down') f = glideAmp / 2 - glideAmp * u
    else f = (glideAmp / 2) * Math.sin(Math.PI * u)
    if (vibAmp) f += vibAmp * Math.sin(2 * Math.PI * (vibratoHz / 9) * u)
    // SVG y grows downward; a rising pitch must rise on screen.
    return mid - f
  }

  // One subpath per note, so the gaps between them are genuinely empty rather
  // than joined by a stray line.
  // Coordinates are rounded hard: x to whole pixels, y to one decimal. The
  // viewBox is only a few hundred units across, so the discarded precision is
  // invisible, and it removes roughly a third of every path string.
  const path = (offset: number, squash: number): string => {
    const steps = STROKE_SAMPLES * notes
    const subpaths: string[] = []
    let current: string[] = []
    for (let i = 0; i <= steps; i++) {
      const x = i / steps
      const u = noteAt(x)
      if (u === null) {
        if (current.length > 1) subpaths.push(`M${current.join('L')}`)
        current = []
        continue
      }
      const y = mid + (contourY(u) - mid) * squash + offset
      current.push(`${Math.round(x * width)},${y.toFixed(1)}`)
    }
    if (current.length > 1) subpaths.push(`M${current.join('L')}`)
    return subpaths.join('')
  }

  // Quick attack, gentle decay — the same note envelope voices.py applies.
  const envelope = (u: number) => (u < 0.1 ? u / 0.1 : 1 - 0.45 * ((u - 0.1) / 0.9))
  const bandHeight = height * 0.13

  // The filled note body, one polygon per note.
  const bands: string[] = []
  for (let n = 0; n < notes; n++) {
    const top: string[] = []
    const bottom: string[] = []
    for (let i = 0; i <= FILL_SAMPLES; i++) {
      const u = i / FILL_SAMPLES
      const px = Math.round(((n + u * (1 - GAP)) / notes) * width)
      top.push(`${px},${(contourY(u) - envelope(u) * bandHeight).toFixed(1)}`)
      bottom.unshift(`${px},${(contourY(u) + envelope(u) * bandHeight).toFixed(1)}`)
    }
    bands.push(
      `<polygon points="${[...top, ...bottom].join(' ')}" fill="${accent}" fill-opacity="0.28"/>`,
    )
  }

  // Faint lanes standing in for the protocol's fixed symbol frequencies.
  // One <path> of horizontal rules rather than seven <line> elements: same
  // picture, a third of the bytes.
  const grid =
    `<path d="${Array.from({ length: 7 }, (_, i) => {
      const y = Math.round((height / 8) * (i + 1))
      return `M0,${y}H${width}`
    }).join('')}" stroke="${base}" stroke-opacity="0.07" stroke-width="1" fill="none"/>`

  // One echo per harmonic above the fundamental, faded by its amplitude. A
  // crow's four loud harmonics read as a thick, crowded mark; a hoopoe's
  // near-pure tone reads as a single clean line.
  const harmonicPaths = harmonics
    .slice(1)
    .map(
      ([, amp], i) =>
        `<path d="${path(-(i + 1) * height * 0.07, 1 + (i + 1) * 0.12)}" fill="none" stroke="${base}" stroke-opacity="${Math.min(amp * 0.55, 0.5).toFixed(2)}" stroke-width="1.2" stroke-linecap="round"/>`,
    )
    .join('')

  const noisePath =
    noise > 0
      ? `<path d="${path(height * 0.09, 1)}" fill="none" stroke="${base}" stroke-opacity="${Math.min(noise * 3.2, 0.45).toFixed(2)}" stroke-width="${Math.min(1 + noise * 14, 5).toFixed(1)}" stroke-dasharray="1 5" stroke-linecap="round"/>`
      : ''

  return [
    // The mark is presentational AT THE SVG LEVEL on purpose. Whatever embeds
    // it supplies the accessible name — <SpeciesArtwork> labels its wrapper,
    // and the OG card rasterises this into an <img>. An inner element also
    // claiming role="img" would be a second, unnamed image announced to a
    // screen reader for every card in the grid.
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="100%" height="100%" preserveAspectRatio="xMidYMid slice" aria-hidden="true" focusable="false">`,
    `<rect width="${width}" height="${height}" fill="${wash}"/>`,
    grid,
    harmonicPaths,
    noisePath,
    bands.join(''),
    `<path d="${path(0, 1)}" fill="none" stroke="${accent}" stroke-width="2.5" stroke-linecap="round"/>`,
    `</svg>`,
  ].join('')
}

/** The same mark as a data: URI, for contexts that only accept an image src. */
export function voiceSignatureDataUri(
  species: Species,
  options?: ArtworkOptions,
): string {
  const svg = voiceSignatureSvg(species, options)
  return `data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`
}
